### ISSUE TITLE
Duplicate/Missing photo issues

### ISSUE THREAD

**Issue by christopher-jones-i3** [chute/photo-picker-plus-android#11]
Our project recently had a round of cleanup that involved removing localized libraries and switching to dependencies that are available through Maven. Photo Picker Plus was included in this cleanup:

```compile 'com.getchute.android.libs.photopickerplus:library:2.0.6'```

However, it appears that these later versions of the library have some strange issues. For instance, when I take photos outside of our app and attempt to find it in the Photo Picker Plus gallery, it is not shown. It seems the Photo Picker Plus library is capable of finding the photos, as the ```LocalServiceType.LAST_PHOTO_TAKEN``` does select the appropriate last photo taken, but it doesn't display outside photos in ```LocalServiceType.ALL_MEDIA```, etc.

Another issue noted is when photos are taken inside the Photo Picker Plus library using the "Take a photo" button. It seems that when a photo is taken, a scaled-down duplicate shows up in subsequent visits to the Photo Picker Plus gallery (in the following example, I have taken only two photos, but two additional scaled duplicates show up):

![allmediaduplicatedownsampledphotos](https://cloud.githubusercontent.com/assets/6749660/6214558/6527ab14-b5c7-11e4-8a76-29830fee7e08.PNG)

I've tested with varying physical devices and Genymotion virtual devices on our project app and on a bare-bones separate app similar to the sample app in this repository.

If any clarification is needed, I can provide more details.

**Comment by olgalazarova** [comment]
Hi Christopher,

We are looking into this issue and will let you know as soon as it gets resolved.

**Comment by christopher-jones-i3** [comment]
@olgalazarova Hey, it looks like the problems reported here have been fixed. I do have one new problem I'll put in a separate issue.
