### ISSUE TITLE
Older versions of OkHttp and Picasso

### ISSUE THREAD

**Issue by GEOZYT** [chute/photo-picker-plus-android#12]
We are trying to use Photo Picker Plus in our project, but we have got a problem because of incompatible versions of some libraries. In particular, Photo Picker Plus depends on OkHttp 1.6.0 (and associated libraries) and Picasso 2.3.2. However, we are using the most recent versions: OkHttp 2.3.0 and Picasso 2.5.2.
A stable version of OkHttp 2.0 was released now more than 9 months ago (now, they have reached version 2.3), so we are wondering whether you plan to migrate soon (given that [incompatible changes do not seem that many](https://github.com/square/okhttp/blob/master/CHANGELOG.md#api-changes) ) We know there might be some other indirect dependencies on OkHttp, but all of them go through other Chute's libraries, thus all is kept in the familiy.
Regarding Picasso, the difference is only minor, so there should not be any incompatible changes (except for... er, the dependency on OkHttp 2.x itself)

We would kindly ask you to migrate and test Photo Picker Plus with OkHttp 2.x, so that projects which are already using that library (such as ours) can use Photo Picker Plus.

**Comment by darko1002001** [comment]
Sorry for the late reply, we somehow missed this issue it seems. The dependencies stretch a bit further than just photo-picker-plus. I have been aware of this for a while now and i released new versions of the networking library we use with the updated dependency to OkHttp, i had to spend some time testing things out first to make sure everything is reliable, now we need to update our SDK's, internal projects and then PP+.

This process will definitely be completed until the end of next week.

**Comment by darko1002001** [comment]
This has been fixed, version 2.2.0 available on Maven.

**Comment by GEOZYT** [comment]
Thanks for the fix!
