### ISSUE TITLE
Crash when in single-selection mode

### ISSUE THREAD

**Issue by christopher-jones-i3** [chute/photo-picker-plus-android#13]
I'm having an issue when using the Photo Picker Plus library in single-selection mode (```isMultiPicker(false)```)

Here is a part of the exception when I tap a photo: "Couldn't read row 0, col -1 from CursorWindow.  Make sure the Cursor is initialized correctly before accessing data from it."

The pertinent part of the exception points to: ```at com.getchute.android.photopickerplus.ui.adapter.CursorAdapterImages$ImageClickListener.onClick(CursorAdapterImages.java:131)```

For clarity, here is a quick run-down of me entering the photo selection area and tapping a photo:
![photopicker](https://cloud.githubusercontent.com/assets/6749660/7121096/f66151cc-e1df-11e4-8c5e-1ee04fee6ad7.gif)

Edit: Forgot to mention I am on version 2.0.7 of the PPP library.

**Comment by darko1002001** [comment]
Thanks for letting us know about this issue. Can you also specify the OS version and device model you are using to test this?

**Comment by christopher-jones-i3** [comment]
I've recently tested this on a Motorola Nexus 6 (at Android 5.1) and a Samsung Galaxy S3 (at Android 4.4.4).

**Comment by christopher-jones-i3** [comment]
When I set ```isMultiPicker(true)```, I have no problems selecting images and returning to my activity. The application I am working on (however) requires that only one photo be selected at a time.

**Comment by darko1002001** [comment]
Ok we will look into this will let you know on this issue when we have it
solved. thanks!

On Mon, Apr 13, 2015 at 8:04 PM, Christopher Jones <notifications@github.com
> wrote:

> When I set isMultiPicker(true), I have no problems selecting images and
> returning to my activity. The application I am working on (however)
> requires that only one photo be selected at a time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chute/photo-picker-plus-android/issues/13#issuecomment-92447309>
> .
>



-- 

Darko Grozdanovski

Developer

Chute <http://getchute.com/> | Blog <http://blog.getchute.com/>

<https://www.facebook.com/darko1002001> <https://twitter.com/darko1002001>
<https://github.com/darko1002001>

**Comment by olgalazarova** [comment]
@christopher-jones-i3 the issue is fixed and it will be deployed soon. thanks!

**Comment by christopher-jones-i3** [comment]
@olgalazarova Do you know when this will be included in a release available through Maven? The latest one I see is 2.0.7 (March, 2015).

**Comment by darko1002001** [comment]
ill deploy it till tomorrow the latest.

**Comment by darko1002001** [comment]
<dependency>
  <groupId>com.getchute.android.libs.photopickerplus</groupId>
  <artifactId>library</artifactId>
  <version>2.0.8</version>
  <type>aar</type>
</dependency>
