### ISSUE TITLE
Build errors after added as a grandle dependency.

### ISSUE THREAD

**Issue by RokasAug** [chute/photo-picker-plus-android#14]
I have added PhotoPicker+ as a gradle dependecy but now I get errors: 
1.
![screen shot 2015-05-19 at 13 05 10](https://cloud.githubusercontent.com/assets/11501440/7700504/db9c00bc-fe27-11e4-9858-1e10b04b11e7.png)

2.
![screen shot 2015-05-19 at 13 06 13](https://cloud.githubusercontent.com/assets/11501440/7700505/db9e1cc6-fe27-11e4-914e-5d14e9b0fa4f.png)

How should i fix it? 
@ozeias , @evandrodutra , @gauravs , @zegomesjf , @bluewhalelabs 
Thanks.

**Comment by darko1002001** [comment]
Hey, just add the code it suggests into your gradle file, it should fix it.

inside:
 android {
}

add:
packagingOptions {
  exclude 'META-INF/LICENSE'
}

**Comment by RokasAug** [comment]
Ohh. I've missed that line, sorry. I had to exclude few more items and it's working now. But my launch activity is now skipped.

**Comment by darko1002001** [comment]
There is no main launcher activity in the library so that is not something that the library affects, look at the sample project for usage.

**Comment by RokasAug** [comment]
Thanks.
